# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_first_name', models.CharField(max_length=300)),
                ('my_last_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='mySchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_school_name', models.TextField()),
                ('my_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.myInfo')),
            ],
        ),
    ]
