# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=800)),
                ('option2', models.CharField(max_length=800)),
                ('option3', models.CharField(max_length=800)),
                ('option4', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_ans', models.CharField(max_length=800)),
            ],
        ),
        migrations.AddField(
            model_name='options',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Questions'),
        ),
    ]
